[general]

[default_bridge]
type=bridge
max_members=20
record_conference=no

[default_user]
type=user
music_on_hold_when_empty=no
quiet=yes
announce_user_count=no

[video_bridge]
type=bridge
max_members=10
record_conference=no
video_mode=sfu
remb_behavior=lowest_all
video_update_discard=2000

[video_user]
type=user
music_on_hold_when_empty=no
quiet=yes
announce_user_count=no
jitterbuffer=no
