[general]
static=yes
writeprotect=yes
clearglobalvars=no

[globals]
CONSOLE=Console/default

[internal]
exten => _[12]XXX,1,NoOp(Internal call ${CALLERID(num)} to ${EXTEN})
 same => n,Set(CDR(userfield)=media=${IF($["${CHANNEL(pjsip,secure)}"="1"]?secure:legacy)})
 same => n,Set(RECORDING_FILE=${UNIQUEID}.wav)
 same => n,MixMonitor(/var/spool/asterisk/monitor/${RECORDING_FILE},b)
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,StopMixMonitor()
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 700,1,Answer()
 same => n,Set(CDR(userfield)=media=conference)
 same => n,ConfBridge(telecom-qa,default_bridge,default_user)
 same => n,Hangup()

exten => 701,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Echo()
 same => n,Hangup()
