[modules]
autoload=yes
preload=res_odbc.so
preload=res_http_websocket.so
preload=res_pjsip_transport_websocket.so
noload=chan_sip.so
noload=cdr_csv.so
noload=cdr_custom.so
noload=cdr_odbc.so
noload=cdr_manager.so
noload=cdr_sqlite3_custom.so
noload=cel_custom.so
noload=cel_manager.so
noload=cel_odbc.so
noload=cel_sqlite3_custom.so
noload=res_phoneprov.so
noload=res_pjsip_phoneprov_provider.so
noload=res_stun_monitor.so
noload=chan_iax2.so
noload=chan_unistim.so
noload=res_hep.so
noload=res_hep_rtcp.so
noload=res_hep_pjsip.so
noload=res_pjsip_notify.so
noload=app_agent_pool.so
noload=app_page.so
noload=res_calendar.so
noload=res_parking.so
noload=app_amd.so
noload=app_alarmreceiver.so
noload=app_festival.so
noload=app_followme.so
noload=app_minivm.so
noload=app_voicemail.so
noload=res_clialiases.so
noload=res_http_media_cache.so
noload=res_prometheus.so
noload=func_odbc.so
noload=app_queue.so
noload=pbx_ael.so
